# Generated by Django 3.2.6 on 2021-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n13', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateField()),
                ('act_type', models.TextField()),
                ('order_numb', models.IntegerField()),
                ('order_date', models.DateField()),
                ('file_path', models.FileField(upload_to='')),
            ],
        ),
    ]
